service: senior-project-template

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1

plugins:
  - serverless-offline

resources:
  Resources:
    EmployeeTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: employees
        AttributeDefinitions:
          - AttributeName: employeeName
            AttributeType: S
        KeySchema:
          - AttributeName: employeeName
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: username
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST



functions:
  login:
    handler: src/handlers/login.handler
    events:
      - http:
          path: login
          method: post
          cors: true
  employeeInfo:
    handler: src/handlers/employeeInfo.handler
    events:
      - http:
          path: employeeInfo
          method: post
          cors: true
